### ISSUE TITLE
Struggling to understand how does it intercept the link and load the content without refreshing 

### ISSUE THREAD

**Issue by shanika** [erikringsmuth/polymer-router-demos#4]
Hi,

I'm just wondering how app-router element intercept the <a> html basic element and just route only the content of routing section without refreshing the whole page. I added few <a> links in my single page app and tried to route using app-router element. But it refreshes the whole page act as a normal link.
I'm new to polymer so may be i'm missing some concepts.

Thanks
Regards
Shanika

**Comment by erikringsmuth** [comment]
The router listens to `popstate` and `hashchange` events. A regular link will do a full page refresh. If you use a hash link like `<a href="#/home">Home</a>` it will trigger a `popstate` event (`hashchange` in old IE) which the router listens to and intercepts.

https://erikringsmuth.github.io/app-router/#/#navigation

https://github.com/erikringsmuth/app-router/blob/master/src/app-router.js#L107-L111

**Comment by shanika** [comment]
Thanks for the quick reply.. now I know what I was missing.. cheers
